### ISSUE TITLE
Finding bytes to write

### ISSUE THREAD

**Issue by michalis97500** [lehnification/hyperx-cloud-alpha-wireless-tray#1]
Hey, would you be interested in explaining what your method was to find the necessary bytes to write in order to get the correct reply? I have a pair of Cloud II wireless and I am making a similar project in python.

**Comment by lehnification** [comment]
Hey, sorry for the late reply, never received a notification.
I used jetbrains dotPeek to decompile the ngenuity software. 
The resulting files for my specific device are attached in the ngenuity folder.
It should be pretty straight forward to find your device once you decompiled it.
